# Generated by Django 6.0.1 on 2026-07-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('recharge', 'Recharge'), ('topup', 'Top Up'), ('pending_bill', 'Pending Bill')], max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('shortcode', models.CharField(max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RechargeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ref', models.CharField(editable=False, max_length=24, unique=True)),
                ('module', models.CharField(choices=[('recharge', 'Recharge'), ('topup', 'Top Up'), ('pending_bill', 'Pending Bill')], default='recharge', max_length=32)),
                ('msisdn', models.CharField(max_length=20)),
                ('customer_name', models.CharField(blank=True, default='', max_length=120)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('amount_pence', models.PositiveIntegerField()),
                ('currency', models.CharField(default='gbp', max_length=3)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending_payment', max_length=20)),
                ('stripe_session_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
