# Generated by Django 6.0 on 2026-08-24 13:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('kind', models.CharField(choices=[('recharge', 'Recharge'), ('topup', 'Top up'), ('pending_bill', 'Pending bill')], default='recharge', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Charged amount. Never accepted from the client.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('transatel_rate_plan', models.CharField(help_text='e.g. "MVNA Wholesale PAYM 7". Sent as ratePlan on reactivate.', max_length=120)),
                ('data_allowance', models.CharField(blank=True, max_length=60)),
                ('validity_days', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recharge plan',
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='RechargeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('sim_serial', models.CharField(db_index=True, max_length=32)),
                ('msisdn', models.CharField(blank=True, max_length=32)),
                ('sim_status_before', models.CharField(blank=True, max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('rate_plan', models.CharField(blank=True, max_length=120)),
                ('stripe_payment_intent_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('transatel_transaction_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('sim_checked', 'SIM checked'), ('payment_pending', 'Payment pending'), ('requires_action', 'Requires action (3DS)'), ('paid', 'Paid — awaiting activation'), ('activated', 'Activated'), ('activation_failed', 'Paid but activation failed'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='initiated', max_length=24)),
                ('failure_reason', models.TextField(blank=True)),
                ('stripe_response', models.JSONField(blank=True, default=dict)),
                ('transatel_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='recharge.rechargeplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recharge_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recharge transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='RechargeModule',
        ),
        migrations.DeleteModel(
            name='RechargeOrder',
        ),
        migrations.AddIndex(
            model_name='rechargetransaction',
            index=models.Index(fields=['user', '-created_at'], name='recharge_re_user_id_398224_idx'),
        ),
        migrations.AddIndex(
            model_name='rechargetransaction',
            index=models.Index(fields=['status', '-created_at'], name='recharge_re_status_e05609_idx'),
        ),
        migrations.AddIndex(
            model_name='rechargetransaction',
            index=models.Index(fields=['sim_serial', '-created_at'], name='recharge_re_sim_ser_48152d_idx'),
        ),
    ]
