# Generated by Django 6.0 on 2026-09-03 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0002_rechargeplan_rechargetransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactivationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_serial', models.CharField(db_index=True, max_length=64)),
                ('rate_plan', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('provider_transaction_id', models.CharField(blank=True, default='', max_length=128)),
                ('error', models.TextField(blank=True, default='')),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RechargeModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('recharge', 'Recharge'), ('topup', 'Top Up'), ('pending_bill', 'Pending Bill')], max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('shortcode', models.CharField(max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RechargeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ref', models.CharField(editable=False, max_length=24, unique=True)),
                ('module', models.CharField(choices=[('recharge', 'Recharge'), ('topup', 'Top Up'), ('pending_bill', 'Pending Bill')], default='recharge', max_length=32)),
                ('msisdn', models.CharField(db_index=True, max_length=20)),
                ('sim_serial', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('sim_iccid', models.CharField(blank=True, default='', max_length=32)),
                ('customer_name', models.CharField(blank=True, default='', max_length=120)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('amount_pence', models.PositiveIntegerField()),
                ('currency', models.CharField(default='gbp', max_length=3)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending_payment', max_length=20)),
                ('stripe_session_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RechargeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('module', models.CharField(choices=[('recharge', 'Recharge'), ('topup', 'Top Up'), ('pending_bill', 'Pending Bill')], db_index=True, default='recharge', max_length=32)),
                ('price_pence', models.PositiveIntegerField(help_text='Price in pence (e.g. 2834 = £28.34)')),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('short_description', models.CharField(blank=True, default='', max_length=512)),
                ('description', models.TextField(blank=True, default='')),
                ('rate_plan', models.CharField(blank=True, default='', max_length=128)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'price_pence'],
            },
        ),
        migrations.CreateModel(
            name='TransatelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('validate_phone', 'Validate Phone'), ('reactivate', 'Reactivate SIM'), ('get_subscriber', 'Get Subscriber')], db_index=True, max_length=32)),
                ('sim_serial_masked', models.CharField(blank=True, default='', max_length=20)),
                ('msisdn_masked', models.CharField(blank=True, default='', max_length=20)),
                ('request_url', models.CharField(blank=True, default='', max_length=512)),
                ('request_method', models.CharField(blank=True, default='', max_length=8)),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('success', models.BooleanField(default=False)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='rechargetransaction',
            name='recharge_re_user_id_398224_idx',
        ),
        migrations.RemoveIndex(
            model_name='rechargetransaction',
            name='recharge_re_status_e05609_idx',
        ),
        migrations.RemoveIndex(
            model_name='rechargetransaction',
            name='recharge_re_sim_ser_48152d_idx',
        ),
        migrations.AddField(
            model_name='reactivationattempt',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactivation_attempts', to='recharge.rechargeorder'),
        ),
        migrations.AddField(
            model_name='rechargeorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='recharge.rechargeproduct'),
        ),
        migrations.AddField(
            model_name='transatellog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transatel_logs', to='recharge.rechargeorder'),
        ),
        migrations.RemoveField(
            model_name='rechargetransaction',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='rechargetransaction',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='reactivationattempt',
            constraint=models.UniqueConstraint(fields=('order', 'sim_serial'), name='uq_reactivation_order_sim'),
        ),
        migrations.DeleteModel(
            name='RechargePlan',
        ),
        migrations.DeleteModel(
            name='RechargeTransaction',
        ),
    ]
