# Generated by Django 6.0.1 on 2026-07-08 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bqorder',
            options={'verbose_name': 'Transatel Order', 'verbose_name_plural': 'Transatel Orders'},
        ),
    ]
