# Generated by Django 6.0.1 on 2026-07-14 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_bqorder_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bqorder',
            options={},
        ),
    ]
