# Generated by Django 6.0.8 on 2026-09-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_checkoutpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutpayment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
