# Generated by Django 6.0.5 on 2026-05-14 09:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MalimaOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='zoiko-orbit-checkout', help_text='Where the request came from. Set by the proxy.', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('partial', 'Partial — some lines failed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('email', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('billing_address', models.JSONField(blank=True, default=dict)),
                ('shipping_address', models.JSONField(blank=True, default=dict)),
                ('stripe_payment_intent_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('bequick_order_id', models.CharField(blank=True, db_index=True, default='', help_text='Kept for legacy / migration cross-references. May be empty.', max_length=64)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-captured_at',),
                'indexes': [models.Index(fields=['status', 'captured_at'], name='malima_mali_status_28f791_idx')],
            },
        ),
        migrations.CreateModel(
            name='SimInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(db_index=True, max_length=20, unique=True)),
                ('imsi', models.CharField(db_index=True, max_length=20, unique=True)),
                ('iccid', models.CharField(db_index=True, max_length=22, unique=True)),
                ('sim_type', models.CharField(choices=[('eSIM', 'eSIM'), ('pSIM', 'pSIM')], db_index=True, default='eSIM', max_length=10)),
                ('roaming_zone', models.CharField(blank=True, db_index=True, default='', help_text="Optional — restrict this SIM to a specific zone (e.g. 'Europe').", max_length=64)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('activated', 'Activated'), ('suspended', 'Suspended'), ('retired', 'Retired'), ('test', 'Test (ACTIVATED_FOR_TEST)')], db_index=True, default='available', max_length=16)),
                ('batch', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SIM inventory',
                'verbose_name_plural': 'SIM inventory',
                'ordering': ('status', 'id'),
                'indexes': [models.Index(fields=['status', 'sim_type', 'roaming_zone'], name='malima_simi_status_290fe9_idx')],
            },
        ),
        migrations.CreateModel(
            name='SimReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('cart_index', models.IntegerField()),
                ('unit_index', models.IntegerField()),
                ('plan_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('consumed', 'Consumed'), ('released', 'Released'), ('expired', 'Expired')], db_index=True, default='active', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='malima.siminventory')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MalimaOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_index', models.IntegerField()),
                ('unit_index', models.IntegerField(default=0)),
                ('plan_id', models.CharField(blank=True, default='', max_length=64)),
                ('plan_name', models.CharField(blank=True, default='', max_length=255)),
                ('sim_type', models.CharField(blank=True, default='', max_length=10)),
                ('msisdn', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('imsi', models.CharField(blank=True, default='', max_length=20)),
                ('iccid', models.CharField(blank=True, db_index=True, default='', max_length=22)),
                ('orange_order_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('http_status', models.IntegerField(default=0)),
                ('ok', models.BooleanField(default=False)),
                ('error', models.CharField(blank=True, default='', max_length=512)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='malima.malimaorder')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='malima.simreservation')),
            ],
            options={
                'ordering': ('order', 'cart_index', 'unit_index'),
            },
        ),
        migrations.AddIndex(
            model_name='simreservation',
            index=models.Index(fields=['status', 'expires_at'], name='malima_simr_status_5f714e_idx'),
        ),
        migrations.AddIndex(
            model_name='malimaorderline',
            index=models.Index(fields=['ok', 'created_at'], name='malima_mali_ok_288842_idx'),
        ),
    ]
