# Generated by Django 6.0 on 2026-03-26 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(default='Short description will be updated', max_length=300)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('software_development', 'Software Development'), ('customer_operations', 'Customer Operations & Loyalty Lifecycle Management'), ('iot_engineering', 'IoT, SIM, & Telematics Engineering'), ('strategic_partnerships', 'Strategic Partnerships & B2B Sales'), ('business_development', 'Business Development Executives'), ('analytics_strategy', 'Analytics, Insights & Performance Strategy')], default='software_development', max_length=50)),
                ('technologies', models.CharField(blank=True, max_length=300, null=True)),
                ('experience', models.CharField(max_length=100)),
                ('positions', models.PositiveIntegerField(default=1)),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
