# Generated by Django 6.0 on 2026-05-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('business_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=50)),
                ('business_website', models.URLField(blank=True, null=True)),
                ('integration_interests', models.JSONField(default=list)),
                ('operating_regions', models.CharField(max_length=255)),
                ('traveler_volume', models.CharField(max_length=100)),
                ('distribution_channels', models.JSONField(default=list)),
                ('business_objective', models.TextField(blank=True, null=True)),
                ('agreed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
