# Generated by Django 6.0.1 on 2026-06-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('subject', models.CharField(choices=[('General Enquiry', 'General Enquiry'), ('Billing', 'Billing'), ('Technical Support', 'Technical Support'), ('Roaming & International', 'Roaming & International'), ('Complaints', 'Complaints'), ('Other', 'Other')], max_length=100)),
                ('message', models.TextField()),
                ('savePref', models.BooleanField(default=False)),
                ('newsletter', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
