"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

load_dotenv()
# BASE_DIR points to the root of your Django project
BASE_DIR = Path(__file__).resolve().parent.parent

# Path where collectstatic will copy all static files
STATIC_URL = '/static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY =  os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"


#ALLOWED_HOSTS = []
ALLOWED_HOSTS = os.getenv(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1"
).split(",")

# Application definition

INSTALLED_APPS = [
    "jazzmin",

 'django.contrib.admin',
    'corsheaders',
   
'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'apps.blog',
      "apps.switch", 
    'apps.business_enterprise',
    'apps.contact',
    'apps.products',
    'apps.accounts',
    'apps.sim_orders',
    'apps.recharge',
    'apps.plans',
    'apps.enterprise',
    'apps.travelpartners',
    'apps.coupons',
    'apps.careers',
     'apps.activation',
    'apps.student_discount',
    # 'apps.first_responder',
    # 'apps.military_discount',
    # 'apps.marine_discount',
    # 'apps.senior_discount',
    'apps.orders',
    'apps.newsletter',
     'apps.news',
    'apps.jobs',
    'apps.search',
    # "apps.transatel",
    'apps.travel_ecosystem_partner',
    'django_ckeditor_5',
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'apps.integrations',
    
    "apps.security",
    "apps.support",
    "apps.sims",
    # 'apps.forms_api',
    # 'apps.demo_api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

CSRF_TRUSTED_ORIGINS = os.getenv(
    "CSRF_TRUSTED_ORIGINS",
    "https://api.zoikomobile.co.uk,https://react.zoikomobile.co.uk,https://zmuk-frontend.vercel.app"
).split(",")


JAZZMIN_SETTINGS = {
    "site_title": " ZoikoMobile Admin",
    "site_header": "Orbit ",
    "site_brand": "ZoikoMobile Admin",
}
ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(DATABASE_URL)
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
    
    
    
    
    
    
    
    
    #csrf
    
    
    CSRF_TRUSTED_ORIGINS = os.getenv(
    "CSRF_TRUSTED_ORIGINS",
    "https://*.onrender.com"
).split(",")
    
    

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|',
            'bold', 'italic', 'link',
            'bulletedList', 'numberedList',
            'blockQuote', 'imageUpload',
            'undo', 'redo'
        ],
    }
}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
           'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 9,
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://zmuk-frontend.vercel.app",
    "http://127.0.0.1:3001",
    "http://localhost:5173",
    "https://golitereact.vercel.app",
    "https://react.golitemobile.com",
    "https://lakhan-golite.vercel.app",
    "https://golitemobile.com",
    "https://www.golitemobile.com",
    "https://zmuk-backend.onrender.com",
    "https://zmuk-frontend.vercel.app",
    
]

# ===============================
# FRONTEND URL (used for verification / reset-password email links)
# ===============================
# FRONTEND_URL is the fallback used when the request's X-Frontend-Origin
# header isn't in FRONTEND_ALLOWED_ORIGINS below. Set this to your real
# production frontend domain once deployed.
FRONTEND_URL = os.getenv(
    "FRONTEND_URL",
    "http://zmuk-frontend.vercel.app"
)
# BACKEND_URL is what gets embedded in the /verify/... link in the
# registration email. Using this instead of request.build_absolute_uri()
# means the link is always reachable, regardless of what host header the
# request happened to arrive on (e.g. 127.0.0.1:8000, which is unreachable
# from a phone). Update this to your real API domain once deployed.
BACKEND_URL = os.getenv(
    "BACKEND_URL",
    "http://127.0.0.1:8000"
)

FRONTEND_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://zmuk-frontend.vercel.app",
    "http://127.0.0.1:3001",
    "http://localhost:5173",
    "https://golitereact.vercel.app",
    "https://react.golitemobile.com",
    "https://lakhan-golite.vercel.app",
    "https://golitemobile.com",
    "https://www.golitemobile.com",
    "http://zmuk-frontend.vercel.app",
    "https://zmuk-backend.onrender.com",
]

CORS_ALLOW_ALL_ORIGINS = True  

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",

    # ✅ ADD THIS
    "x-frontend-origin",
]


CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",  
    "OPTIONS",
]


USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')





# stripe keys 

STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")

STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY")

STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET")






# ===============================9999999999999
# EMAIL / SMTP CONFIGURATION
# ===============================

EMAIL_BACKEND =  os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend"
)








EMAIL_HOST = os.getenv("EMAIL_HOST")

EMAIL_PORT = int(os.getenv("EMAIL_PORT", "465"))

EMAIL_USE_TLS = os.getenv(
    "EMAIL_USE_TLS",
    "False"
) == "True"

EMAIL_USE_SSL = os.getenv(
    "EMAIL_USE_SSL",
    "True"
) == "True"

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")

EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")

DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")

TEST_RECEIVER_EMAIL = os.getenv("TEST_RECEIVER_EMAIL")