"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.
"""

from pathlib import Path
import os

import dj_database_url
from dotenv import load_dotenv

load_dotenv()

# =============================================================================
# BASE
# =============================================================================

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.getenv("SECRET_KEY")

DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = os.getenv(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1,api.zoikomobile.co.uk,.onrender.com",
).split(",")

# =============================================================================
# CSRF
# =============================================================================

CSRF_TRUSTED_ORIGINS = os.getenv(
    "CSRF_TRUSTED_ORIGINS",
    "https://api.zoikomobile.co.uk,"
    "https://react.zoikomobile.co.uk,"
    "https://zmuk-frontend.vercel.app,"
    "http://localhost:3000,"
    "http://localhost:3001,"
    "http://127.0.0.1:3000,"
    "http://127.0.0.1:8000",
).split(",")

# =============================================================================
# APPLICATIONS
# =============================================================================

INSTALLED_APPS = [
    "jazzmin",

    "django.contrib.admin",
    "corsheaders",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "core",

    # Project apps
    "apps.blog",
    "apps.switch",
    "apps.business_enterprise",
    "apps.contact",
    "apps.products",
    "apps.accounts",
    "apps.sim_orders",

    # Recharge - ONLY ONCE
    "apps.recharge",

    "apps.plans",
    "apps.enterprise",
    "apps.travelpartners",
    "apps.coupons",
    "apps.careers",
    "apps.activation",
    "apps.student_discount",
    "apps.newsletter",
    "apps.news",
    "apps.jobs",
    "apps.search",
    "apps.travel_ecosystem_partner",
    "apps.integrations",
    "apps.security",
    "apps.support",
    "apps.sims",

    # Third-party apps
    "django_ckeditor_5",
    "rest_framework",
    "rest_framework.authtoken",
    "django_filters",
    "django_extensions",
]

# =============================================================================
# MIDDLEWARE
# =============================================================================

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

WSGI_APPLICATION = "core.wsgi.application"

# =============================================================================
# JAZZMIN
# =============================================================================

JAZZMIN_SETTINGS = {
    "site_title": "ZoikoMobile Admin",
    "site_header": "Orbit",
    "site_brand": "ZoikoMobile Admin",
}

# =============================================================================
# TEMPLATES
# =============================================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# =============================================================================
# DATABASE
# =============================================================================

DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(DATABASE_URL)
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# =============================================================================
# PASSWORD VALIDATION
# =============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]

# =============================================================================
# INTERNATIONALIZATION
# =============================================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# =============================================================================
# STATIC / MEDIA
# =============================================================================

STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"

# =============================================================================
# CKEDITOR
# =============================================================================

CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": [
            "heading",
            "|",
            "bold",
            "italic",
            "link",
            "bulletedList",
            "numberedList",
            "blockQuote",
            "imageUpload",
            "undo",
            "redo",
        ],
    },
}

# =============================================================================
# DJANGO REST FRAMEWORK
# =============================================================================

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_PAGINATION_CLASS": (
        "rest_framework.pagination.PageNumberPagination"
    ),
    "PAGE_SIZE": 9,
    # Conservative default rate limits — no endpoint had any limit before.
    # Individual views can still override with their own throttle_classes.
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",
        "user": "1000/hour",
    },
}

# =============================================================================
# CORS
# =============================================================================

CORS_ALLOWED_ORIGINS = os.getenv(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:3000,"
    "http://127.0.0.1:3000,"
    "http://localhost:3001,"
    "http://127.0.0.1:3001,"
    "https://react.zoikomobile.co.uk",
).split(",")

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-frontend-origin",
]

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]

# =============================================================================
# FRONTEND / BACKEND URLS
# =============================================================================

FRONTEND_URL = os.getenv(
    "FRONTEND_URL",
    "https://react.zoikomobile.co.uk",
)

BACKEND_URL = os.getenv(
    "BACKEND_URL",
    "http://127.0.0.1:8000",
)

FRONTEND_ALLOWED_ORIGINS = os.getenv(
    "FRONTEND_ALLOWED_ORIGINS",
    "https://react.zoikomobile.co.uk,"
    "http://localhost:3000,"
    "http://127.0.0.1:3000",
).split(",")

# =============================================================================
# PROXY / HTTPS
# =============================================================================

USE_X_FORWARDED_HOST = True

SECURE_PROXY_SSL_HEADER = (
    "HTTP_X_FORWARDED_PROTO",
    "https",
)

# =============================================================================
# STRIPE
# =============================================================================

STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")

STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY")

STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET")

# =============================================================================
# TRANSATEL / RECHARGE
# =============================================================================

TRANSATEL_BASE = os.getenv(
    "TRANSATEL_BASE",
    "https://api.transatel.com",
)

TRANSATEL_CLIENT_ID = os.getenv(
    "TRANSATEL_CLIENT_ID",
    "",
)

TRANSATEL_CLIENT_SECRET = os.getenv(
    "TRANSATEL_CLIENT_SECRET",
    "",
)

TRANSATEL_TIMEOUT = int(
    os.getenv("TRANSATEL_TIMEOUT", "30")
)

# Dict consumed by apps.sims.transatel.config.get_config()
# Maps your env vars to the keys the config module expects.
TRANSATEL = {
    "API_BASE_URL": TRANSATEL_BASE,
    "AUTH_ENDPOINT": "/authentication/api/token",
    "CLIENT_ID": TRANSATEL_CLIENT_ID,
    "CLIENT_SECRET": TRANSATEL_CLIENT_SECRET,
    "RATE_PLAN": os.getenv("TRANSATEL_RATE_PLAN", "MVNA Wholesale PAYM 7"),
    "GROUP": os.getenv("TRANSATEL_GROUP", "ZOIKO eSIM"),
    "DEFAULT_COUNTRY_OF_RESIDENCE": "UK",
    "TOKEN_REFRESH_BUFFER": 300,
    "REQUEST_TIMEOUT": TRANSATEL_TIMEOUT,
}

# Only SIMs with this status can be recharged.
RECHARGE_ALLOWED_SIM_STATUSES = [
    "suspended",
]

# =============================================================================
# EMAIL / SMTP
# =============================================================================

EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend",
)

EMAIL_HOST = os.getenv("EMAIL_HOST")

EMAIL_PORT = int(
    os.getenv("EMAIL_PORT", "465")
)

EMAIL_USE_TLS = os.getenv(
    "EMAIL_USE_TLS",
    "False",
) == "True"

EMAIL_USE_SSL = os.getenv(
    "EMAIL_USE_SSL",
    "True",
) == "True"

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")

EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")

DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")

TEST_RECEIVER_EMAIL = os.getenv("TEST_RECEIVER_EMAIL")

# =============================================================================
# BLOG EMAIL NOTIFICATIONS
# =============================================================================

SITE_NAME = os.getenv(
    "SITE_NAME",
    "Zoiko Mobile",
)

BLOG_NOTIFY_ON_PUBLISH = (
    os.getenv(
        "BLOG_NOTIFY_ON_PUBLISH",
        "True",
    ) == "True"
)

BLOG_NOTIFICATION_ADMIN_EMAIL = (
    os.getenv(
        "BLOG_NOTIFICATION_ADMIN_EMAIL"
    ) or None
)

BLOG_NOTIFICATION_BATCH_SIZE = int(
    os.getenv(
        "BLOG_NOTIFICATION_BATCH_SIZE",
        "40",
    )
)

EMAIL_TIMEOUT = int(
    os.getenv(
        "EMAIL_TIMEOUT",
        "20",
    )
)

# =============================================================================
# MEDIA / STATIC STORAGE
# =============================================================================

USE_S3 = os.getenv(
    "USE_S3",
    "False",
) == "True"

if USE_S3:

    AWS_ACCESS_KEY_ID = os.getenv(
        "AWS_ACCESS_KEY_ID"
    )

    AWS_SECRET_ACCESS_KEY = os.getenv(
        "AWS_SECRET_ACCESS_KEY"
    )

    AWS_STORAGE_BUCKET_NAME = os.getenv(
        "AWS_STORAGE_BUCKET_NAME"
    )

    AWS_S3_ENDPOINT_URL = (
        os.getenv("AWS_S3_ENDPOINT_URL") or None
    )

    AWS_S3_CUSTOM_DOMAIN = (
        os.getenv("AWS_S3_CUSTOM_DOMAIN") or None
    )

    AWS_S3_REGION_NAME = os.getenv(
        "AWS_S3_REGION_NAME",
        "auto",
    )

    AWS_QUERYSTRING_AUTH = False

    AWS_DEFAULT_ACL = None

    AWS_S3_FILE_OVERWRITE = False

    AWS_S3_OBJECT_PARAMETERS = {
        "CacheControl": "max-age=86400"
    }

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
        },
        "staticfiles": {
            "BACKEND": (
                "whitenoise.storage."
                "CompressedStaticFilesStorage"
            ),
        },
    }

else:

    STORAGES = {
        "default": {
            "BACKEND": (
                "django.core.files.storage."
                "FileSystemStorage"
            ),
        },
        "staticfiles": {
            "BACKEND": (
                "whitenoise.storage."
                "CompressedStaticFilesStorage"
            ),
        },
    }

# =============================================================================
# LOGGING
# =============================================================================

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "simple": {
            "format": (
                "[{levelname}] {asctime} "
                "{name}: {message}"
            ),
            "style": "{",
        },
    },

    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },

    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },

    "loggers": {
        "apps.blog": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },

        "apps.recharge": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },

        "apps.sims.transatel": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },

        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}
# =============================================================================
# PRODUCTION SECURITY (only active when DEBUG=False)
# =============================================================================

if not DEBUG:
    # HTTPS enforcement
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Cookie security
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True

    # Prevent content-type sniffing
    SECURE_CONTENT_TYPE_NOSNIFF = True

    # Clickjacking protection
    X_FRAME_OPTIONS = "DENY"

# =============================================================================
# RECHARGE BEHAVIOUR
# =============================================================================

# Set True to block non-suspended SIMs from proceeding to recharge.
# Default False = matches WordPress: lets everything through, gates at
# reactivation time instead.
RECHARGE_BLOCK_NON_SUSPENDED = os.getenv(
    "RECHARGE_BLOCK_NON_SUSPENDED", "False"
) == "True"
