# Generated by Django 6.0 on 2026-05-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('business_email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('Owner', 'Owner'), ('Manager', 'Manager'), ('Agent', 'Agent'), ('Other', 'Other')], max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('enquiry_type', models.CharField(choices=[('Corporate Travel', 'Corporate Travel'), ('Remote Workforce', 'Remote Workforce'), ('API Integration', 'API Integration'), ('Custom Program', 'Custom Program')], max_length=100)),
                ('message', models.TextField()),
                ('consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
