# Generated by Django 6.0 on 2026-05-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelEcosystemPartnerInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('work_email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('country_region', models.CharField(max_length=255)),
                ('role_function', models.CharField(max_length=255)),
                ('monthly_traveler_volume', models.CharField(choices=[('0-1K', '0-1K'), ('1K-10K', '1K-10K'), ('10K-50K', '10K-50K'), ('50K-100K', '50K-100K'), ('100K+', '100K+')], max_length=100)),
                ('partnership_interest', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
