# Generated by Django 6.0.1 on 2026-05-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_ecosystem_partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelecosystempartnerinquiry',
            name='monthly_traveler_volume',
            field=models.CharField(choices=[('0-1K', '0-1K'), ('1K-10K', '1K-10K'), ('10K-50K', '10K-50K'), ('50K-100K', '50K-100K'), ('100K-200K', '100K-200K'), ('200K+', '200K+')], max_length=100),
        ),
    ]
