# Generated by Django 6.0.1 on 2026-06-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_plan_data_allowance_plan_price_12_plan_price_30_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='transatelID,',
        ),
        migrations.AddField(
            model_name='plan',
            name='transatelID',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
