# Generated by Django 6.0.1 on 2026-06-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_remove_plan_transatelid__plan_transatelid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='transatelID',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
