# Generated by Django 6.0.1 on 2026-06-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_alter_plan_transatelid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='transatelID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
