# Generated by Django 6.0.1 on 2026-05-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('business_email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('Owner', 'Owner'), ('Manager', 'Manager'), ('Agent', 'Agent'), ('Other', 'Other')], max_length=50)),
                ('website', models.URLField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
