# Generated by Django 6.0.1 on 2026-05-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelpartners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpartner',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
