# Generated by Django 6.0.7 on 2026-07-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, default='', max_length=64)),
                ('iccid', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='ICCID')),
                ('imsi', models.CharField(blank=True, default='', max_length=32, verbose_name='IMSI')),
                ('msisdn', models.CharField(blank=True, default='', max_length=24, verbose_name='MSISDN')),
                ('type_of_sim', models.CharField(blank=True, default='', max_length=64)),
                ('sim_reference', models.CharField(blank=True, default='', max_length=64)),
                ('provisioning_status', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('prepaid_status', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('subscriber', models.CharField(blank=True, default='', max_length=128)),
                ('company', models.CharField(blank=True, default='', max_length=128)),
                ('reference', models.CharField(blank=True, default='', max_length=64)),
                ('customer_account', models.CharField(blank=True, default='', max_length=128)),
                ('group', models.CharField(blank=True, default='', max_length=128)),
                ('point_of_sale', models.CharField(blank=True, default='', max_length=64)),
                ('first_activation_date', models.DateTimeField(blank=True, null=True)),
                ('last_action_date', models.DateTimeField(blank=True, null=True)),
                ('last_seen_date', models.DateTimeField(blank=True, null=True)),
                ('provisioning_action_number', models.CharField(blank=True, default='', max_length=64)),
                ('subscriber_number', models.CharField(blank=True, default='', max_length=64)),
                ('service_pack', models.CharField(blank=True, default='', max_length=128)),
                ('service_profile', models.CharField(blank=True, default='', max_length=128)),
                ('rate_plan', models.CharField(blank=True, default='', max_length=128)),
                ('last_imei', models.CharField(blank=True, default='', max_length=32, verbose_name='Last IMEI')),
                ('last_origin_country', models.CharField(blank=True, default='', max_length=64)),
                ('last_mcc', models.CharField(blank=True, default='', max_length=8, verbose_name='Last MCC')),
                ('last_mnc', models.CharField(blank=True, default='', max_length=8, verbose_name='Last MNC')),
                ('last_rat', models.CharField(blank=True, default='', max_length=8, verbose_name='Last RAT')),
                ('last_destination', models.CharField(blank=True, default='', max_length=64)),
                ('data_usage_gb', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('voice_usage', models.CharField(blank=True, default='', max_length=32)),
                ('sms_usage', models.CharField(blank=True, default='', max_length=32)),
                ('mms_usage', models.CharField(blank=True, default='', max_length=32)),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SIM',
                'verbose_name_plural': 'SIMs',
                'ordering': ['provisioning_status', '-first_activation_date', 'iccid'],
            },
        ),
    ]
