# Generated by Django 6.0 on 2026-07-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimCartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ref', models.CharField(editable=False, max_length=24, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('customer_name', models.CharField(blank=True, default='', max_length=160)),
                ('order_type', models.CharField(default='sim', max_length=20)),
                ('status', models.CharField(choices=[('received', 'Received'), ('pending_payment', 'Pending payment'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='received', max_length=20)),
                ('raw_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
