# Generated by Django 6.0 on 2026-06-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SwitchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('postcode', models.CharField(max_length=255)),
                ('current_provider', models.CharField(blank=True, choices=[('EE', 'EE'), ('O2', 'O2'), ('Vodafone', 'Vodafone'), ('Three', 'Three'), ('BT Mobile', 'BT Mobile'), ('Sky Mobile', 'Sky Mobile'), ('Tesco Mobile', 'Tesco Mobile'), ('giffgaff', 'giffgaff'), ('Other', 'Other')], max_length=50)),
                ('current_plan_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('current_data_allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('selected_plan', models.CharField(choices=[('Zoiko Unlimited Data', 'Zoiko Unlimited Data'), ('Zoiko Elite 100GB', 'Zoiko Elite 100GB'), ('Zoiko Max 30GB', 'Zoiko Max 30GB'), ('Zoiko Standard 10GB', 'Zoiko Standard 10GB'), ('Zoiko Plus 3GB', 'Zoiko Plus 3GB'), ('Zoiko Connect 1GB', 'Zoiko Connect 1GB')], max_length=100)),
                ('transfer_authorised', models.BooleanField(default=False)),
                ('timeline_acknowledged', models.BooleanField(default=False)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('pac_code', models.CharField(blank=True, max_length=20)),
                ('stac_code', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Switch Request',
                'verbose_name_plural': 'Switch Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
