# Generated by Django 6.0 on 2026-07-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDiscountApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('institution', models.CharField(max_length=255)),
                ('student_id_number', models.CharField(max_length=100)),
                ('enrolment_status', models.CharField(max_length=150)),
                ('graduation_date', models.DateField()),
                ('selected_plan', models.CharField(max_length=255)),
                ('contract_duration', models.CharField(max_length=100)),
                ('roaming', models.BooleanField(default=False)),
                ('wifi_calling', models.BooleanField(default=False)),
                ('esim', models.BooleanField(default=False)),
                ('student_id_document', models.FileField(upload_to='student-discount/')),
                ('signature', models.CharField(max_length=255)),
                ('declaration_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Discount Application',
                'verbose_name_plural': 'Student Discount Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
