# Generated by Django 6.0 on 2026-03-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('position_applied', models.CharField(choices=[('Software Development', 'Software Development'), ('Customer Operations & Loyalty Lifecycle Management', 'Customer Operations & Loyalty Lifecycle Management'), ('IoT, SIM, & Telematics Engineering', 'IoT, SIM, & Telematics Engineering'), ('Strategic Partnerships & B2B Sales', 'Strategic Partnerships & B2B Sales'), ('Business Development Executives', 'Business Development Executives'), ('Analytics, Insights & Performance Strategy', 'Analytics, Insights & Performance Strategy')], max_length=200)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
