# Generated by Django 6.0.1 on 2026-05-13 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enterpriseinquiry',
            options={'verbose_name': 'Enterprise', 'verbose_name_plural': 'Enterprise'},
        ),
        migrations.RenameField(
            model_name='enterpriseinquiry',
            old_name='country_region',
            new_name='country',
        ),
    ]
