# Generated by Django 6.0.1 on 2026-05-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_alter_enterpriseinquiry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseinquiry',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
